services:
 postgres:
  image: postgres
  environment:
   - POSTGRES_PASSWORD=87113400
  ports:
   - 5431:5432
  volumes:
   - pgdata:/var/lib/postgresql/data
 mongodb:
  image: mongo
  environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=87113400
  ports:
    - 27017:27017
  volumes:
    - mongodata:/var/lib/mongodb/data
  
volumes:
  pgdata:
  mongodata: